//! The committed `STATUS.md`: one row per program with the outcome of each step under both
//! fields, the cross-field verdict and a fingerprint of the underlying records. Regenerated by
//! `make status` and checked by CI.

use std::collections::BTreeMap;
use std::fmt;
use std::path::PathBuf;

use sha2::{Digest, Sha256};

use super::capability::{Capability, FieldDescriptor};
use super::corpus::{
    CorpusProgram, check_checkout_matches_stamp, corpus_dir, field_tag, fixtures_dir, hex,
    list_programs, noir_checkout, provenance, referee_dir, run_record,
};
use super::diff::{
    CrossFieldDump, DiffOutcome, DumpProvenance, FailureKind, RunRecord, StepOutcome,
    is_coverage_gap, outcome_is_tolerated, outcomes_equivalent,
};
use super::projection::PROJECTION_VERSION;

/// Rows for the referee's own fixtures carry this prefix.
const FIXTURE_PREFIX: &str = "fixtures/";

fn status_path() -> PathBuf {
    referee_dir().join("STATUS.md")
}

fn dump_dir() -> PathBuf {
    referee_dir().join("target/status")
}

fn dump_path(tag: &str) -> PathBuf {
    dump_dir().join(format!("{tag}.json"))
}

/// Programs whose inputs or recorded return need a field property; a side whose field lacks it
/// cannot run them.
const PROGRAM_CAPABILITIES: &[(&str, &[Capability])] = &[
    ("bit_shifts_runtime", &[Capability::SignedFits(64)]),
    ("bit_shifts_u128", &[Capability::UnsignedFits(128)]),
    ("regression_7962", &[Capability::UnsignedFits(64)]),
    ("regression_8009", &[Capability::SignedFits(64)]),
    ("regression_8261", &[Capability::FieldBitsAtLeast(254)]),
    ("regression_8726", &[Capability::SignedFits(64)]),
    (
        "regression_brillig_const_fold_self_dedup",
        &[Capability::FieldBitsAtLeast(254)],
    ),
    (
        "regression_struct_array_conditional",
        &[Capability::FieldBitsAtLeast(254)],
    ),
    ("signed_truncation", &[Capability::SignedFits(64)]),
    ("unsigned_to_signed_cast", &[Capability::UnsignedFits(64)]),
    (
        "fixtures/neg_interp_inputs_i64",
        &[Capability::SignedFits(64)],
    ),
];

/// Programs whose divergence is field-dependent by design. Each entry must keep diverging, and
/// none covers a panic or an internal error.
const KNOWN_FIELD_DEPENDENT: &[(&str, &str)] = &[
    (
        "modulus",
        "asserts modulus_num_bits() == 254 and compares the modulus bytes and bits with bn254's",
    ),
    (
        "field_attribute",
        "defines foo() under #[field(bn254)], #[field(23)] and #[field(bls12_381)] only; no arm \
         exists for goldilocks",
    ),
    (
        "regression_8519",
        "asserts (-a) as u128 against a constant derived from the bn254 modulus and records that \
         u128 as the return",
    ),
    (
        "cast_regression_7776",
        "casts a - (c as Field) to u64 with inputs that make it -1 mod p, whose low 64 bits are \
         field-specific",
    ),
    (
        "to_le_bytes",
        "to_le_bytes::<31> exceeds the Goldilocks 8-byte modulus size",
    ),
    (
        "to_be_bytes",
        "to_be_bytes::<31> exceeds the Goldilocks 8-byte modulus size",
    ),
    (
        "to_bytes_consistent",
        "to_be_bytes::<31> exceeds the Goldilocks 8-byte modulus size",
    ),
    (
        "to_bytes_integration",
        "to_*_bytes::<31/32> and to_le_bits::<254> plus modulus_* builtins are field-sized",
    ),
    (
        "regression_7128",
        "to_be_bytes::<32> exceeds the Goldilocks 8-byte modulus size",
    ),
    (
        "unrolling_regression_8333",
        "to_be_bytes::<32> exceeds the Goldilocks 8-byte modulus size",
    ),
    (
        "brillig_cow_regression",
        "to_be_bytes::<32> exceeds the Goldilocks 8-byte modulus size",
    ),
    (
        "vectors",
        "to_be_bytes::<32> exceeds the Goldilocks 8-byte modulus size",
    ),
    (
        "multi_scalar_mul",
        "to_be_bits::<254> exceeds the Goldilocks 64-bit modulus size",
    ),
];

/// Fixtures that reach no field-gated code, so they must project identically under both fields.
const PROJECTION_INVARIANT_FIXTURES: &[&str] = &[
    "interp_inputs_u64",
    "interp_inputs_i32",
    "interp_inputs_struct",
    "interp_inputs_mixed",
    "interp_refs_call_chain",
    "interp_match_enum",
    "interp_match_int",
];

fn allowlist_reason(name: &str) -> Option<&'static str> {
    KNOWN_FIELD_DEPENDENT
        .iter()
        .find(|(entry, _)| *entry == name)
        .map(|(_, reason)| *reason)
}

/// The first tagged capability of `name` that `field` lacks.
fn predicted_gap(name: &str, field: &FieldDescriptor) -> Option<Capability> {
    PROGRAM_CAPABILITIES
        .iter()
        .find(|(entry, _)| *entry == name)
        .and_then(|(_, tags)| tags.iter().copied().find(|tag| !tag.holds(field)))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Verdict {
    /// A workspace manifest: the referee runs neither side.
    NotRun,
    /// Same value, or the same failure kind.
    Equal,
    /// Same value up to `Field` elements.
    EqualModuloField,
    /// One side cannot run the program and a capability tag says why.
    PredictedGap,
    /// A divergence or gap the allowlist records as field-dependent by design.
    FieldDependent,
    /// One side reaches stdlib code that does not elaborate under its field.
    DependencyGap,
    /// Neither side ran the program: interpreter coverage debt.
    CoverageGap,
    /// One side cannot run the program and nothing predicts it.
    UnexpectedGap,
    /// Different values, a value against an error, different error kinds, a panic or an internal
    /// error.
    Divergence,
}

impl fmt::Display for Verdict {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Verdict::NotRun => "➖ not run",
            Verdict::Equal => "✅ equal",
            Verdict::EqualModuloField => "✅ equal*",
            Verdict::PredictedGap => "🟡 predicted",
            Verdict::FieldDependent => "🟡 field-dependent",
            Verdict::DependencyGap => "🟡 dependency",
            Verdict::CoverageGap => "🟡 both-sides",
            Verdict::UnexpectedGap => "⚠️ unexpected",
            Verdict::Divergence => "❌ divergence",
        })
    }
}

fn outcome_label(outcome: &DiffOutcome) -> String {
    match outcome {
        DiffOutcome::Returned(_) => "returned".to_string(),
        DiffOutcome::Errored { error, .. } => error.kind.to_string(),
    }
}

fn is_hard_failure(outcome: &DiffOutcome) -> bool {
    matches!(
        outcome,
        DiffOutcome::Errored { error, .. }
            if matches!(error.kind, FailureKind::Panic | FailureKind::Internal)
    )
}

/// The divergence class for a mismatched outcome pair.
fn divergence_bucket(a: &DiffOutcome, b: &DiffOutcome) -> &'static str {
    let has = |kind: FailureKind| {
        matches!(a, DiffOutcome::Errored { error, .. } if error.kind == kind)
            || matches!(b, DiffOutcome::Errored { error, .. } if error.kind == kind)
    };
    if has(FailureKind::Panic) {
        return "panic";
    }
    if has(FailureKind::Internal) {
        return "internal_error";
    }
    match (a, b) {
        (DiffOutcome::Returned(_), DiffOutcome::Returned(_)) => "value_mismatch",
        (DiffOutcome::Returned(_), DiffOutcome::Errored { .. })
        | (DiffOutcome::Errored { .. }, DiffOutcome::Returned(_)) => "returned_vs_errored",
        (DiffOutcome::Errored { .. }, DiffOutcome::Errored { .. }) => "kind_mismatch",
    }
}

/// Panics and internal errors are never field-dependent by design.
fn divergence_is_allowlistable(a: &DiffOutcome, b: &DiffOutcome) -> bool {
    !is_hard_failure(a) && !is_hard_failure(b)
}

struct Sides<'a> {
    bn254: &'a FieldDescriptor,
    goldilocks: &'a FieldDescriptor,
}

/// Classify one program's pair of outcomes (`a` under bn254, `b` under goldilocks).
fn classify(name: &str, a: &DiffOutcome, b: &DiffOutcome, sides: &Sides<'_>) -> (Verdict, String) {
    let allowlisted = allowlist_reason(name);
    match outcomes_equivalent(a, b) {
        Err(reason) => {
            let input_gap = match (a, b) {
                (DiffOutcome::Returned(_), DiffOutcome::Errored { error, .. })
                    if error.kind == FailureKind::InputError =>
                {
                    Some(("goldilocks", sides.goldilocks))
                }
                (DiffOutcome::Errored { error, .. }, DiffOutcome::Returned(_))
                    if error.kind == FailureKind::InputError =>
                {
                    Some(("bn254", sides.bn254))
                }
                _ => None,
            };
            if let Some((side, field)) = input_gap {
                if let Some(tag) = predicted_gap(name, field) {
                    return (
                        Verdict::PredictedGap,
                        format!("{side} lacks: {}", tag.describe()),
                    );
                }
            }
            match allowlisted {
                Some(why) if divergence_is_allowlistable(a, b) => {
                    (Verdict::FieldDependent, format!("{why}; {reason}"))
                }
                _ => (
                    Verdict::Divergence,
                    format!("{}: {reason}", divergence_bucket(a, b)),
                ),
            }
        }
        Ok(()) if outcome_is_tolerated(a, b) => {
            let (gap_a, gap_b) = (is_coverage_gap(a), is_coverage_gap(b));
            if gap_a && gap_b {
                return (
                    Verdict::CoverageGap,
                    format!("{} / {}", outcome_label(a), outcome_label(b)),
                );
            }
            let (side, gap, other, field) = if gap_a {
                ("bn254", a, b, sides.bn254)
            } else {
                ("goldilocks", b, a, sides.goldilocks)
            };
            let DiffOutcome::Errored { error, .. } = gap else {
                unreachable!("a coverage gap is an errored outcome");
            };
            if error.kind == FailureKind::DependencyCompileGap {
                let note = match allowlisted {
                    Some(why) => format!("{side}: {}; allowlisted: {why}", error.payload),
                    None => format!("{side}: {}", error.payload),
                };
                return (Verdict::DependencyGap, note);
            }
            if let Some(tag) = predicted_gap(name, field) {
                return (
                    Verdict::PredictedGap,
                    format!("{side} lacks: {}", tag.describe()),
                );
            }
            if !matches!(other, DiffOutcome::Returned(_)) {
                return (
                    Verdict::CoverageGap,
                    format!(
                        "{side}: {}; other side: {}",
                        error.kind,
                        outcome_label(other)
                    ),
                );
            }
            match allowlisted {
                Some(why) => (
                    Verdict::FieldDependent,
                    format!("{side}: {}; {why}", error.kind),
                ),
                None => (
                    Verdict::UnexpectedGap,
                    format!("{side}: {} with no capability predicting it", error.kind),
                ),
            }
        }
        Ok(()) => match (a, b) {
            (DiffOutcome::Returned(x), DiffOutcome::Returned(y)) if x == y => {
                (Verdict::Equal, String::new())
            }
            (DiffOutcome::Returned(_), DiffOutcome::Returned(_)) => {
                (Verdict::EqualModuloField, String::new())
            }
            _ => (Verdict::Equal, format!("both: {}", outcome_label(a))),
        },
    }
}

struct Row {
    name: String,
    bn254: [&'static str; 3],
    goldilocks: [&'static str; 3],
    verdict: Verdict,
    ast: &'static str,
    record: String,
}

fn glyph(step: &StepOutcome) -> &'static str {
    match step {
        StepOutcome::Passed => "✅",
        StepOutcome::Failed { .. } => "❌",
        StepOutcome::NotRun { .. } => "➖",
    }
}

/// `compile`, `run`, `return`; a load failure counts as a compile failure.
fn step_glyphs(record: &RunRecord) -> [&'static str; 3] {
    let compile = match (&record.load, &record.compile) {
        (StepOutcome::NotRun { .. }, _) => "➖",
        (StepOutcome::Failed { .. }, _) => "❌",
        (StepOutcome::Passed, compile) => glyph(compile),
    };
    [compile, glyph(&record.interpret), glyph(&record.oracle)]
}

fn ast_glyph(a: &RunRecord, b: &RunRecord) -> &'static str {
    match (&a.projection_hash, &b.projection_hash) {
        (Some(x), Some(y)) if x == y => "✅",
        (Some(_), Some(_)) => "❌",
        _ => "➖",
    }
}

/// Eight hex digits over both records' source hash, step outcomes with their payloads, returned
/// values and projection hashes; triage detail is left out.
fn fingerprint(a: &RunRecord, b: &RunRecord) -> String {
    let mut hasher = Sha256::new();
    for record in [a, b] {
        hasher.update(record.source_hash.as_bytes());
        for step in [
            &record.load,
            &record.compile,
            &record.interpret,
            &record.oracle,
            &record.projection,
        ] {
            hasher.update(step.render().as_bytes());
            hasher.update(b"\n");
        }
        if let Some(value) = &record.returned {
            hasher.update(value.render().as_bytes());
        }
        hasher.update(b"\n");
        hasher.update(
            record
                .projection_hash
                .as_deref()
                .unwrap_or_default()
                .as_bytes(),
        );
        hasher.update(b"\n");
    }
    hex(&hasher.finalize())[..8].to_string()
}

fn row(name: &str, a: &RunRecord, b: &RunRecord, sides: &Sides<'_>) -> Row {
    let not_run = |record: &RunRecord| matches!(record.load, StepOutcome::NotRun { .. });
    let (verdict, ast) = if not_run(a) || not_run(b) {
        (Verdict::NotRun, "➖")
    } else {
        (
            classify(name, &a.outcome(), &b.outcome(), sides).0,
            ast_glyph(a, b),
        )
    };
    Row {
        name: name.to_string(),
        bn254: step_glyphs(a),
        goldilocks: step_glyphs(b),
        verdict,
        ast,
        record: fingerprint(a, b),
    }
}

const HEADER: &str = "| Program | bn254 compile | bn254 run | bn254 return | goldilocks compile | goldilocks run | goldilocks return | Fields | AST | Record |\n\
     | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n";

fn render_status(bn254: &DumpProvenance, goldilocks: &DumpProvenance, rows: &[Row]) -> String {
    let mut out = String::from(
        "# Status\n\n\
         Every program of Noir's `execution_success` corpus and this crate's fixtures, compiled \
         and interpreted under both fields at the pinned compiler revision. `compile`, `run` and \
         `return` are the frontend, the interpreter and the check against the `return` recorded in \
         `Prover.toml` (exact under bn254; `Field` values ignored under goldilocks, whose corpus \
         records bn254 values). `Fields` is the cross-field verdict; `equal*` means only `Field` \
         values differ. `AST` says whether both monomorphized programs project to the same hash. \
         `Record` fingerprints the row's underlying records, so any change shows here even when \
         the glyphs do not. Regenerate with `make status`; CI fails when a fresh run differs.\n\n",
    );
    let fixtures = rows
        .iter()
        .filter(|row| row.name.starts_with(FIXTURE_PREFIX))
        .count();
    out.push_str(&format!(
        "| provenance | value |\n| --- | --- |\n\
         | noir_rev | {} |\n| corpus_hash | {} |\n| programs | {} corpus, {fixtures} fixtures |\n\
         | toolchain | {} |\n| format | dump {}, projection {} |\n\n",
        bn254.noir_rev,
        bn254.corpus_hash,
        bn254.program_count,
        bn254.toolchain,
        bn254.format_version,
        bn254.projection_version
    ));
    debug_assert_eq!(bn254.format_version, goldilocks.format_version);

    out.push_str(HEADER);
    for row in rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            row.name,
            row.bn254[0],
            row.bn254[1],
            row.bn254[2],
            row.goldilocks[0],
            row.goldilocks[1],
            row.goldilocks[2],
            row.verdict,
            row.ast,
            row.record
        ));
    }

    out.push_str("\n## Totals\n\n| column | ✅ | ❌ | ➖ |\n| --- | --- | --- | --- |\n");
    let columns: [(&str, fn(&Row) -> &'static str); 7] = [
        ("bn254 compile", |r| r.bn254[0]),
        ("bn254 run", |r| r.bn254[1]),
        ("bn254 return", |r| r.bn254[2]),
        ("goldilocks compile", |r| r.goldilocks[0]),
        ("goldilocks run", |r| r.goldilocks[1]),
        ("goldilocks return", |r| r.goldilocks[2]),
        ("AST", |r| r.ast),
    ];
    for (label, column) in columns {
        let count = |glyph: &str| rows.iter().filter(|r| column(r) == glyph).count();
        out.push_str(&format!(
            "| {label} | {} | {} | {} |\n",
            count("✅"),
            count("❌"),
            count("➖")
        ));
    }
    out.push_str("\n| Fields | count |\n| --- | --- |\n");
    for verdict in [
        Verdict::Equal,
        Verdict::EqualModuloField,
        Verdict::PredictedGap,
        Verdict::FieldDependent,
        Verdict::DependencyGap,
        Verdict::CoverageGap,
        Verdict::UnexpectedGap,
        Verdict::Divergence,
        Verdict::NotRun,
    ] {
        let count = rows.iter().filter(|r| r.verdict == verdict).count();
        out.push_str(&format!("| {verdict} | {count} |\n"));
    }
    out
}

fn records_for(
    programs: &[CorpusProgram],
    prefix: &str,
    done: &mut usize,
    total: usize,
) -> Vec<(String, RunRecord)> {
    programs
        .iter()
        .map(|program| {
            *done += 1;
            eprintln!("[{done}/{total}] {}{}", prefix, program.name);
            (format!("{prefix}{}", program.name), run_record(program))
        })
        .collect()
}

/// `make sweep FIELD=<field>`: record the corpus and the fixtures under this build into
/// `target/status/<field>.json`.
#[test]
#[ignore = "status: run `make sweep FIELD=<field>`"]
fn dump_records() {
    let checkout = noir_checkout();
    check_checkout_matches_stamp(&checkout).unwrap_or_else(|e| panic!("{e}"));
    let corpus = corpus_dir();
    let programs = list_programs(&corpus);
    assert!(
        !programs.is_empty(),
        "no programs under {}",
        corpus.display()
    );
    let fixtures = list_programs(&fixtures_dir());

    let total = programs.len() + fixtures.len();
    let mut done = 0;
    let mut records = records_for(&programs, "", &mut done, total);
    records.extend(records_for(&fixtures, FIXTURE_PREFIX, &mut done, total));
    check_checkout_matches_stamp(&checkout).unwrap_or_else(|e| panic!("{e}"));

    let dump = CrossFieldDump {
        provenance: provenance(&corpus, &programs),
        records,
    };
    let json = serde_json::to_string_pretty(&dump).unwrap();
    let restored = super::diff::parse_dump(&json).unwrap();
    assert_eq!(restored, dump, "dump must round-trip through JSON");

    std::fs::create_dir_all(dump_dir()).unwrap();
    let path = dump_path(field_tag());
    std::fs::write(&path, &json).unwrap();
    let returned = dump
        .records
        .iter()
        .filter(|(_, r)| r.returned.is_some())
        .count();
    println!(
        "recorded {} programs ({returned} returned a value) under {} at noir {}: {}",
        dump.records.len(),
        field_tag(),
        dump.provenance.noir_rev,
        path.display()
    );
}

/// `make render`: classify every program across the two field dumps and write `STATUS.md`.
/// Divergences are rows; only harness invariants fail the test.
#[test]
#[ignore = "status: run `make render`"]
fn render_status_file() {
    let load = |tag: &str| -> CrossFieldDump {
        let path = dump_path(tag);
        let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "missing the {tag} dump at {} ({e}); run `make sweep FIELD={tag}` first",
                path.display()
            )
        });
        super::diff::parse_dump(&text).unwrap_or_else(|e| panic!("{tag} dump: {e}"))
    };
    let (bn254, goldilocks) = (load("bn254"), load("goldilocks"));

    let (pa, pb) = (&bn254.provenance, &goldilocks.provenance);
    assert_eq!(
        (pa.field.as_str(), pb.field.as_str()),
        ("bn254", "goldilocks")
    );
    assert_ne!(
        pa.field_modulus, pb.field_modulus,
        "both dumps are the same field"
    );
    for (p, tag) in [(pa, "bn254"), (pb, "goldilocks")] {
        assert_eq!(
            p.projection_version, PROJECTION_VERSION,
            "the {tag} dump has a stale projection version"
        );
    }
    assert_eq!(
        pa.noir_rev, pb.noir_rev,
        "dumps built against different noir revisions"
    );
    assert_eq!(
        pa.interpreter_rev, pb.interpreter_rev,
        "dumps built against different referee revisions"
    );
    assert_eq!(
        pa.toolchain, pb.toolchain,
        "dumps built with different Rust toolchains"
    );
    assert_eq!(
        pa.corpus_hash, pb.corpus_hash,
        "dumps photograph different corpora"
    );
    assert_eq!(pa.program_count, pb.program_count);

    let sides = Sides {
        bn254: &FieldDescriptor::new(&pa.field, pa.field_modulus.parse().unwrap()),
        goldilocks: &FieldDescriptor::new(&pb.field, pb.field_modulus.parse().unwrap()),
    };
    let bn: BTreeMap<String, RunRecord> = bn254.records.into_iter().collect();
    let gl: BTreeMap<String, RunRecord> = goldilocks.records.into_iter().collect();

    let mut rows: Vec<Row> = Vec::new();
    let mut missing: Vec<String> = Vec::new();
    let mut value_pairs = 0usize;
    for (name, a) in &bn {
        let Some(b) = gl.get(name) else {
            missing.push(format!("{name} (only in bn254)"));
            continue;
        };
        assert_eq!(
            a.source_hash, b.source_hash,
            "{name} sources differ between field dumps"
        );
        if a.returned.is_some() && b.returned.is_some() {
            value_pairs += 1;
        }
        rows.push(row(name, a, b, &sides));
    }
    missing.extend(
        gl.keys()
            .filter(|name| !bn.contains_key(*name))
            .map(|name| format!("{name} (only in goldilocks)")),
    );

    let path = status_path();
    std::fs::write(&path, render_status(pa, pb, &rows)).unwrap();

    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for row in &rows {
        *counts.entry(row.verdict.to_string()).or_default() += 1;
    }
    println!(
        "compared {} programs: {counts:?}; wrote {}",
        rows.len(),
        path.display()
    );

    let stale: Vec<&str> = KNOWN_FIELD_DEPENDENT
        .iter()
        .map(|(name, _)| *name)
        .filter(|name| {
            let row = rows.iter().find(|row| row.name == *name);
            row.is_none_or(|row| matches!(row.verdict, Verdict::Equal | Verdict::EqualModuloField))
        })
        .collect();
    let projection_drift: Vec<String> = PROJECTION_INVARIANT_FIXTURES
        .iter()
        .map(|name| format!("{FIXTURE_PREFIX}{name}"))
        .filter_map(|name| rows.iter().find(|row| row.name == name))
        .filter(|row| row.ast != "✅")
        .map(|row| format!("{} ({})", row.name, row.ast))
        .collect();

    assert!(
        missing.is_empty(),
        "programs missing from one dump: {}",
        missing.join(", ")
    );
    assert!(
        value_pairs > 0,
        "no program returned a value under both fields"
    );
    assert!(
        stale.is_empty(),
        "allowlisted program(s) absent or no longer diverging; remove from KNOWN_FIELD_DEPENDENT: {}",
        stale.join(", ")
    );
    assert!(
        projection_drift.is_empty(),
        "field-independent fixtures project differently across fields: {}",
        projection_drift.join(", ")
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diff::{ComparableError, DiffValue};

    fn bn254() -> FieldDescriptor {
        FieldDescriptor::new(
            "bn254",
            "21888242871839275222246405745257275088548364400416034343698204186575808495617"
                .parse()
                .unwrap(),
        )
    }

    fn goldilocks() -> FieldDescriptor {
        FieldDescriptor::new("goldilocks", "18446744069414584321".parse().unwrap())
    }

    fn returned(value: &str) -> DiffOutcome {
        DiffOutcome::Returned(DiffValue::Int {
            signed: false,
            bits: 64,
            value: value.parse().unwrap(),
        })
    }

    fn errored(kind: FailureKind, payload: &str) -> DiffOutcome {
        DiffOutcome::Errored {
            error: ComparableError::new(kind, payload),
            detail: String::new(),
        }
    }

    fn unsupported(construct: &str) -> DiffOutcome {
        errored(
            FailureKind::Unsupported {
                construct: construct.to_string(),
            },
            construct,
        )
    }

    fn verdict(name: &str, a: &DiffOutcome, b: &DiffOutcome) -> (Verdict, String) {
        let (bn, gl) = (bn254(), goldilocks());
        classify(
            name,
            a,
            b,
            &Sides {
                bn254: &bn,
                goldilocks: &gl,
            },
        )
    }

    #[test]
    fn equal_values_and_field_only_differences_are_told_apart() {
        assert_eq!(
            verdict("p", &returned("1"), &returned("1")).0,
            Verdict::Equal
        );
        let (a, b) = (
            DiffOutcome::Returned(DiffValue::Field("1".into())),
            DiffOutcome::Returned(DiffValue::Field("2".into())),
        );
        assert_eq!(verdict("p", &a, &b).0, Verdict::EqualModuloField);
        assert_eq!(
            verdict("p", &returned("1"), &returned("2")).0,
            Verdict::Divergence
        );
    }

    #[test]
    fn a_one_sided_gap_needs_a_prediction() {
        let (v, note) = verdict("p", &returned("1"), &unsupported("intrinsic"));
        assert_eq!(v, Verdict::UnexpectedGap);
        assert!(note.contains("goldilocks"), "{note}");

        let (v, note) = verdict(
            "bit_shifts_runtime",
            &returned("1"),
            &unsupported("signed 64-bit ABI input is not representable in this field"),
        );
        assert_eq!(v, Verdict::PredictedGap);
        assert!(note.contains("i64 encodes injectively"), "{note}");
        assert_eq!(
            verdict("bit_shifts_runtime", &unsupported("x"), &returned("1")).0,
            Verdict::UnexpectedGap
        );
    }

    #[test]
    fn gaps_beside_errors_dependency_gaps_and_two_sided_gaps_are_named() {
        let (v, note) = verdict(
            "p",
            &unsupported("intrinsic"),
            &errored(FailureKind::CompileError, "no impl"),
        );
        assert_eq!(v, Verdict::CoverageGap);
        assert!(note.contains("CompileError"), "{note}");
        let dep = errored(FailureKind::DependencyCompileGap, "std/field/mod.nr");
        let (v, note) = verdict("p", &returned("1"), &dep);
        assert_eq!(v, Verdict::DependencyGap);
        assert!(note.contains("std/field/mod.nr"), "{note}");
        let (v, _) = verdict("p", &unsupported("intrinsic"), &unsupported("oracle call"));
        assert_eq!(v, Verdict::CoverageGap);
    }

    #[test]
    fn rejected_inputs_are_a_predicted_gap_only_under_a_tag() {
        let rejected = errored(FailureKind::InputError, "value too large");
        let (v, note) = verdict("bit_shifts_u128", &returned("1"), &rejected);
        assert_eq!(v, Verdict::PredictedGap);
        assert!(note.contains("u128 fits"), "{note}");
        assert_eq!(
            verdict("p", &returned("1"), &rejected).0,
            Verdict::Divergence
        );
        assert_eq!(
            verdict("bit_shifts_u128", &rejected, &returned("1")).0,
            Verdict::Divergence
        );
    }

    #[test]
    fn a_workspace_manifest_is_a_not_run_row() {
        let (bn, gl) = (bn254(), goldilocks());
        let sides = Sides {
            bn254: &bn,
            goldilocks: &gl,
        };
        let mut skipped = record(None, "1");
        skipped.load = StepOutcome::not_run("workspace manifest");
        skipped.projection_hash = None;
        let row = row("ws", &skipped, &skipped, &sides);
        assert_eq!(row.verdict, Verdict::NotRun);
        assert_eq!(row.bn254, ["➖", "✅", "➖"]);
    }

    #[test]
    fn the_allowlist_covers_divergences_but_never_crashes() {
        let assertion = errored(FailureKind::AssertionFailed, "x");
        assert_eq!(
            verdict("to_be_bytes", &returned("1"), &assertion).0,
            Verdict::FieldDependent
        );
        assert_eq!(
            verdict("other", &returned("1"), &assertion).0,
            Verdict::Divergence
        );
        let panic = errored(FailureKind::Panic, "boom");
        let (v, note) = verdict("to_be_bytes", &returned("1"), &panic);
        assert_eq!(v, Verdict::Divergence);
        assert!(note.starts_with("panic"), "{note}");
        assert!(!divergence_is_allowlistable(&returned("1"), &panic));
        assert!(!divergence_is_allowlistable(
            &errored(FailureKind::Internal, ""),
            &returned("1")
        ));
    }

    fn record(returned: Option<DiffValue>, projection: &str) -> RunRecord {
        RunRecord {
            source_hash: "ab".repeat(32),
            load: StepOutcome::Passed,
            compile: StepOutcome::Passed,
            interpret: StepOutcome::Passed,
            oracle: StepOutcome::not_run("no recorded return"),
            projection: StepOutcome::Passed,
            returned,
            projection_hash: Some(projection.repeat(64)),
        }
    }

    fn provenance_for(field: &str, modulus: &str) -> DumpProvenance {
        DumpProvenance {
            format_version: 3,
            projection_version: PROJECTION_VERSION,
            field: field.to_string(),
            field_modulus: modulus.to_string(),
            noir_rev: "deadbeef".to_string(),
            interpreter_rev: "cafe".to_string(),
            interpreter_dirty: false,
            corpus_dir: "/x".to_string(),
            corpus_hash: "01".repeat(32),
            program_count: 1,
            toolchain: "rustc 1.89.0".to_string(),
            features: Vec::new(),
            built_at: "0".to_string(),
        }
    }

    fn render(rows: &[Row]) -> String {
        render_status(
            &provenance_for("bn254", "7"),
            &provenance_for("goldilocks", "5"),
            rows,
        )
    }

    #[test]
    fn rows_carry_glyphs_ast_agreement_and_a_detail_free_fingerprint() {
        let (bn, gl) = (bn254(), goldilocks());
        let sides = Sides {
            bn254: &bn,
            goldilocks: &gl,
        };
        let ok = record(Some(DiffValue::Unit), "1");
        let same = row("p", &ok, &ok, &sides);
        assert_eq!((same.verdict, same.ast), (Verdict::Equal, "✅"));
        assert_eq!(same.bn254, ["✅", "✅", "➖"]);
        assert_eq!(
            row("p", &ok, &record(Some(DiffValue::Unit), "2"), &sides).ast,
            "❌"
        );

        let mut failed = record(None, "1");
        failed.interpret = StepOutcome::failed(
            ComparableError::new(FailureKind::Panic, "stable cause"),
            "first/path.nr:12",
        );
        failed.projection = StepOutcome::failed(
            ComparableError::new(FailureKind::Panic, "projection panic"),
            "triage",
        );
        failed.projection_hash = None;
        let broken = row("q", &ok, &failed, &sides);
        assert_eq!(broken.goldilocks, ["✅", "❌", "➖"]);
        assert_eq!((broken.verdict, broken.ast), (Verdict::Divergence, "➖"));
        let mut other_detail = failed.clone();
        other_detail.interpret = StepOutcome::failed(
            ComparableError::new(FailureKind::Panic, "stable cause"),
            "other/path.nr:34",
        );
        assert_eq!(fingerprint(&ok, &failed), fingerprint(&ok, &other_detail));
        let mut other_payload = failed.clone();
        other_payload.interpret =
            StepOutcome::failed(ComparableError::new(FailureKind::Panic, "other cause"), "");
        assert_ne!(fingerprint(&ok, &failed), fingerprint(&ok, &other_payload));
        assert_ne!(
            fingerprint(&ok, &ok),
            fingerprint(&ok, &record(Some(DiffValue::Bool(true)), "1"))
        );
    }

    #[test]
    fn status_rendering_is_deterministic_and_omits_triage_fields() {
        let (bn, gl) = (bn254(), goldilocks());
        let sides = Sides {
            bn254: &bn,
            goldilocks: &gl,
        };
        let ok = record(Some(DiffValue::Str("with | pipe".into())), "1");
        let mut failed = ok.clone();
        failed.oracle = StepOutcome::failed(
            ComparableError::new(FailureKind::OracleMismatch, "integer differs"),
            "triage detail",
        );
        let rows = [
            row("a_prog", &ok, &failed, &sides),
            row(&format!("{FIXTURE_PREFIX}fix"), &ok, &ok, &sides),
        ];
        let text = render(&rows);
        assert_eq!(text, render(&rows));
        assert!(
            text.contains("| a_prog | ✅ | ✅ | ➖ | ✅ | ✅ | ❌ | ✅ equal | ✅ | "),
            "{text}"
        );
        assert!(text.contains("| fixtures/fix | ✅ | ✅ | ➖ | ✅ | ✅ | ➖ | ✅ equal | ✅ | "));
        assert!(text.contains("| programs | 1 corpus, 1 fixtures |"));
        assert!(text.contains("| goldilocks return | 0 | 1 | 1 |"));
        assert!(text.contains("| ✅ equal | 2 |"));
        for triage in [
            "cafe",
            "/x",
            "built_at",
            "interpreter_rev",
            "triage detail",
            "pipe",
        ] {
            assert!(
                !text.contains(triage),
                "{triage} must not reach STATUS.md:\n{text}"
            );
        }
    }
}
